# Generated by Django 2.1.1 on 2018-10-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='comuna',
        ),
    ]
